// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZFpmPQ-HUdtz1fyLt3CgLEvapa12_Lo0',
    appId: '1:727289924074:web:206246684d32b5695a8a93',
    messagingSenderId: '727289924074',
    projectId: 'ecommrceapp-28945',
    authDomain: 'ecommrceapp-28945.firebaseapp.com',
    storageBucket: 'ecommrceapp-28945.firebasestorage.app',
    measurementId: 'G-905D74BX0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP8wEKoB_Zw364CShrtZvbk2ML0kbpUOY',
    appId: '1:727289924074:android:c2e34cb84413ee1e5a8a93',
    messagingSenderId: '727289924074',
    projectId: 'ecommrceapp-28945',
    storageBucket: 'ecommrceapp-28945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjxv7s_TMzLBTvVuJK89HmceKdwWseLKg',
    appId: '1:727289924074:ios:44d4904ede057d7d5a8a93',
    messagingSenderId: '727289924074',
    projectId: 'ecommrceapp-28945',
    storageBucket: 'ecommrceapp-28945.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjxv7s_TMzLBTvVuJK89HmceKdwWseLKg',
    appId: '1:727289924074:ios:44d4904ede057d7d5a8a93',
    messagingSenderId: '727289924074',
    projectId: 'ecommrceapp-28945',
    storageBucket: 'ecommrceapp-28945.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZFpmPQ-HUdtz1fyLt3CgLEvapa12_Lo0',
    appId: '1:727289924074:web:17025547423907bc5a8a93',
    messagingSenderId: '727289924074',
    projectId: 'ecommrceapp-28945',
    authDomain: 'ecommrceapp-28945.firebaseapp.com',
    storageBucket: 'ecommrceapp-28945.firebasestorage.app',
    measurementId: 'G-6YGQ4JBLF8',
  );
}
